Make retry cound and delay into input parameters
sekassel-research/actions-rancher-update pull request #12
Opened 2022-11-28 13:00 UTC by augusto-herrmann

Adds to new input parameters:

- `retry_count`: Maximum number of retries waiting for upgrade
- `retry_delay`: Timeout before retry waiting for upgrade

Those options may be useful for people still using Rancher 1.x.

Fixes #8

2022-12-05 06:34 UTC, youngjin-yun-kurly commented
👍

2023-03-30 06:32 UTC, cryptiklemur commented
Can we get a merge here @Clashsoft ?

2023-03-30 18:24 UTC, cryptiklemur commented
For anyone stuck here, can use `economiagovbr/actions-rancher-update@rancher-1.6.x` until this is merged

2023-03-31 16:41 UTC, Clashsoft requested changes

2023-03-31 16:41 UTC, Clashsoft commented on main.js
> +  let retry = retry_count;
Please use camelCase. Also, the retry variable can be removed and the parameter can be used as the counter.

2023-03-31 16:41 UTC, Clashsoft commented on action.yml
> +    required: true
Please don't make this required, instead use the previous values as defaults.

2023-03-31 16:41 UTC, Clashsoft commented
I can merge this as soon as the requested changes are resolved.

2023-03-31 16:43 UTC, Clashsoft commented on action.yml
> +    required: true
Also, please document the new parameters in the Readme.

2023-04-04 01:51 UTC, aequasi commented
Good now?

2023-04-04 02:08 UTC, aequasi commented on main.js
>    if (retry === 0) {
retry here isnt defined

2023-04-04 13:23 UTC, augusto-herrmann commented on main.js
>    if (retry === 0) {
good catch!

2023-04-05 22:52 UTC, Clashsoft requested changes

2023-04-05 22:52 UTC, Clashsoft commented on README.md
> +          retry_delay: 5
```suggestion
          retry_count: 10 # optional
          retry_delay: 5 # optional
```

2023-04-05 22:52 UTC, Clashsoft commented on main.js
> +  const RETRY_DELAY = core.getInput('retry_delay', { required: true });
```suggestion
  const RETRY_COUNT = +core.getInput('retry_count');
  const RETRY_DELAY = +core.getInput('retry_delay');
```

2023-04-07 10:42 UTC, merged